# .github/workflows/schedule.yml
name: Github Actions Demo

on:
  schedule:
    - cron: '* * * * *'  # Every minute
  workflow_dispatch:      # Add manual trigger for testing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Hello World"
